[package]
name = "s2p"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.15"
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
anyhow = "1.0.99"
bytes = "1.10.1"
iroh = "0.91.1"
n0-future = "0.2.0"
log = "0.4.27"
env_logger = "0.11.6"
pin-project = "1.1.10"
tracing = "0.1.41"